### PR TITLE
added new options to support turning off bold highlighting

### PR DESCRIPTION
**Pull request by adros**
fixex #79 

`--bold=false` or `--no-bold` option may now be used

### CODE REVIEW

**Comment by gkz** [comment]
Maybe "no-colour" should turn off bolding as well?

**Comment by adros** [comment]
Ok, but if one option should be responsible for both color and bold, I would pick a different name, e.g. `--no-highlight`. So maybe for backward compatibility `color` and `bold` options will be better. 

But it's up to you. I can submit new pull request with your suggestion if you want.

**Comment by adros** [comment]
what about this? it's stacked for a month..

**Comment by gkz** [comment]
I don't know what's the right choice. I'm leaning toward having `no-color` also remove bolding.

**Comment by adros** [comment]
Well, I tried to rewrite it to your approach. But it seems that all your tests rely on 'bold' character being presented in result. So changing it in this way would require rewriting also all the tests. 
(or changing this method in test/_helpers.ls to just strip all '#' characters, but then it would not have much sense to use '#' in tests and then just strip them')

    embolden = ->
      if typeof! it is 'String'
        it.replace /##/g '\u001b[1m' .replace /#/g '\u001b[22m'
      else
        it

**Comment by gkz** [comment]
OK, so my plan is to change the way the tests work, and have `--no-color` turn off bolding as well (which seems to be `grep`s behaviour).

**Comment by gkz** [comment]
I will merge this for now, and deal with fixing the tests a later time (combining the functionality under the no-color flag)

**Pull request merged**
